### PR TITLE
Save window bounds

### PR DESCRIPTION
**Pull request by G07cha**
Exporting started work from #109 

TODO: 
- Try to integrate with Terminal class

### CODE REVIEW

**Comment by shockone** [comment]
@G07cha do you need some help?

**Comment by G07cha** [comment]
@shockone, current implementation is ready to use but according to your suggestion remains only replace save defaults using fs with Terminal class. If you can implement this feature I would be thankful.

**Comment by shockone** [comment]
@G07cha, oh, sorry, I haven't noticed it's finished.

**Comment by G07cha** [comment]
For now I participate in ua-web-challange so can't spend enough time to learn TypeScript.

**Comment by shockone** [comment]
@G07cha I wish you luck!

**Comment by G07cha** [comment]
Thanks, after I finish with challenge I'll return back to this task.

**Comment by shockone** [comment]
@G07cha, I've implemented remembering size and position a bit differently. Closing this PR.

**Pull request closed without merging**
