### PR TITLE
Build Automation & Continuous Integration

### PR DESCRIPTION
**Pull request by joshtoo**
#63 Shared branch for Travis-ci work by @joshtoo & @jcgertig

### CODE REVIEW

**Comment by shockone** [comment]
@joshtoo, do  you have enough permissions to set up the hooks?

**Comment by joshtoo** [comment]
@shockone - No. For the moment I have my fork in Travis to work through build issues

**Comment by shockone** [comment]
@joshtoo please let me know when you need any configuration changes then.

**Comment by G07cha** [comment]
Can we also add deploy settings?
```
deploy:
  provider: releases
  api-key: "GITHUB OAUTH TOKEN"
  file:
    - "OS X build"
    - "Windows build"
    - "Linux build"
  skip_cleanup: true
  on:
    tags: true
```
[Source](http://docs.travis-ci.com/user/deployment/releases/)

**Comment by joshtoo** [comment]
@G07cha - No problem.

**Comment by G07cha** [comment]
@joshtoo also suggest to add OAuth token to enviroment variables in Travis instead of inserting into config file.

**Pull request closed without merging**
