### PR TITLE
Include prerequisites in README install instructions.

### PR DESCRIPTION
**Pull request by xtoddx**
This is a small change to README.md that makes mention of how to install node and use npm to install bower globally. These are required to complete the first `npm install` step of the installation instructions.

Since on most machines this will already be done, and is not specific to black-screen, I created a `prerequistes` section in the README so most people can just skip over it.

### CODE REVIEW

**Comment by G07cha** [comment]
Bower is in dependencies already so it must be installed with npm install command.

**Comment by G07cha** [comment]
Also I like compact model, like [this one](https://github.com/ekonstantinidis/gitify#prerequisites).

**Comment by shockone** [comment]
@xtoddx, I agree with @G07cha. We do expect some level of knowledge from our users (prerequisites, huh?). I think it's hard to find a developer who doesn't know how to install node.js.

**Comment by xtoddx** [comment]
Maybe we were racing each other :racehorse:  #89 landed after my fork, it fixes the use of bower in a `preinstall` script.

**Comment by shockone** [comment]
@xtoddx that's true. Thank you for help in any case.

**Pull request closed without merging**
