### PR TITLE
Updated .gitignore for OSX; A new icon

### PR DESCRIPTION
**Pull request by mzgnr**

### CODE REVIEW

**Comment by G07cha** [comment]
:+1:

**Comment by mzgnr** [comment]
New application icon added with this pull request.

**Comment by G07cha** [comment]
Icorrect name for icon, application build points to icon.icons, you can change the name of your icon or change `--icon` attribute [in this line](https://github.com/black-screen/black-screen/blob/master/package.json#L63)

**Comment by G07cha** [comment]
Looks great but icon have white border, can you fix this? That would be awesome.
screen shot 2015-09-08 at 11 22 46 am
screen shot 2015-09-08 at 11 22 27 am

**Comment by mzgnr** [comment]
I'm on it. But I can't pack application for some reason. I get a white screen and a couple of errors after packing.
screen shot 2015-09-08 at 11 33 03

**Comment by G07cha** [comment]
I'm trying to find problem, for now check if main.js and all.css exists if `/Applicatons/Black Screen-darwin-x64/Black Screen.app/Contents/Resurces/app/compiled`, if not copy them from `compiled` folder

**Comment by shockone** [comment]
Could you please name the file `black-screen.icns` for consistency?

**Comment by mzgnr** [comment]
Roger; I'll update.

**Comment by mzgnr** [comment]
Icon is updated.

screen shot 2015-09-08 at 14 41 44
screen shot 2015-09-08 at 14 42 34

**Comment by G07cha** [comment]
:+1:

**Comment by G07cha** [comment]
Actually we still have two icons, we have two solutions for this:
1. Remove icon.icons and create folder icon where place new one
2. Replace icon.icons with new one

As I know @shockone prefer second solution.

**Comment by G07cha** [comment]
Alright, finally, just delete icons folder

**Comment by mzgnr** [comment]
finally :flushed:

**Comment by shockone** [comment]
Should I merge, or are you still working on it?

**Comment by G07cha** [comment]
:+1:

**Comment by G07cha** [comment]
@shockone, I don't have suggestions, if you too, let's merge it.

**Comment by shockone** [comment]
I don't have them either, but I'd like to hear from @mzgnr.

**Comment by mzgnr** [comment]
I think it looks nice. I'm working on a web design for this project. I want to focus on it if you don't have any suggestions .

**Comment by shockone** [comment]
@mzgnr thank you for the beautiful icon. Can't wait to see the design.

**Comment by jdsimcoe** [comment]
@shockone @mzgnr The new Application icon is beautiful but not sized the same as other circular icons. Does anyone have the source files to make this adjustment. Here is a screenshot for reference:

60tufvgrtbhyn-gqthg-roumujjrpozwb45ptcd9nc4

**Comment by jdsimcoe** [comment]
@mzgnr @shockone Any thoughts about the app icon being larger than other circular icons on OS X?

**Comment by shockone** [comment]
@jdsimcoe I can see it bothers you a lot. :) I would love if somebody fixed it; @mzgnr should have the source file, let's hope he'll share it with us.

**Comment by jdsimcoe** [comment]
@shockone I'm cursed being a designer and having things bother me. If @mzgnr shares the source file I can update it.

**Comment by shockone** [comment]
@jdsimcoe it you (as a designer) feel you can write a new better icon, we might use yours.

**Comment by jdsimcoe** [comment]
Done.

https://github.com/black-screen/black-screen/pull/166

**Pull request merged**
